events {
    worker_connections 1024;  # 每个 worker 进程可以建立的最大连接数
}

http {
    # 配置代理缓存路径和规则
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=10g inactive=60m use_temp_path=off;

    # 定义一个名为 myapp 的 upstream，用于负载均衡
    upstream myapp {
        server localhost:8080 weight=3;  # 后端服务器1，权重3
        server localhost:8081 weight=2;  # 后端服务器2，权重2
        server localhost:8082 weight=1;  # 后端服务器3，权重1
    }

    # server 块定义了一个服务
    server {
        listen 80;  # 监听 80 端口

        # 根路径的配置
        location / {
            proxy_pass http://myapp;  # 请求转发到 myapp
            # 设置 HTTP 头部，用于记录客户端真实 IP 和协议
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # /login 路径的配置
        location /login {
            proxy_pass http://myapp;  # 请求转发到 myapp
            proxy_cache my_cache;  # 使用 my_cache 缓存
            proxy_cache_valid 200 302 10m;  # 缓存有效时间为 10 分钟
            proxy_cache_methods POST;  # 允许缓存 POST 请求
        }

        # /register 路径的配置
        location /register {
            proxy_pass http://myapp;  # 请求转发到 myapp
            proxy_cache my_cache;  # 使用 my_cache 缓存
            proxy_cache_valid 200 302 10m;  # 缓存有效时间为 10 分钟
            proxy_cache_methods POST;  # 允许缓存 POST 请求
        }
    }
}
